name: CI for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Test Backend
        run: |
          cd backend
          npm install
          npm test

      - name: Install and Test Frontend
        run: |
          cd frontend
          npm install
          npm test
