name: CI/CD for Main Branch

on:
  push:
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Test Backend
        run: |
          cd backend
          npm install
          npm test

      - name: Install and Test Frontend
        run: |
          cd frontend
          npm install
          npm test

      - name: Merge to Main
        uses: devcinci/merge-branch@v2.0.1
        with:
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
